name: Universal Build
on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string
jobs:
  build-universal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
      - name: build
        run: gradle -Prelease=true -PreproducibleBuild=true -Pversion=${{ inputs.project-version }} build
      - name: zip
        shell: bash
        run: zip -j build/libs/smart-cache-cli-${{ inputs.project-version }}.jar smart-cache-cli-${{ inputs.project-version }}.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
            retention-days: 5
            name: universal
            path: |
              smart-cache-cli-${{ inputs.project-version }}.zip
